package com.yang.pojo;

import java.util.Date;

public class Logs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_id
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_title
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    private String logTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_content
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    private String logContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logs.log_date
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    private Date logDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_id
     *
     * @return the value of logs.log_id
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_id
     *
     * @param logId the value for logs.log_id
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_title
     *
     * @return the value of logs.log_title
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public String getLogTitle() {
        return logTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_title
     *
     * @param logTitle the value for logs.log_title
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public void setLogTitle(String logTitle) {
        this.logTitle = logTitle == null ? null : logTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_content
     *
     * @return the value of logs.log_content
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public String getLogContent() {
        return logContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_content
     *
     * @param logContent the value for logs.log_content
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public void setLogContent(String logContent) {
        this.logContent = logContent == null ? null : logContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logs.log_date
     *
     * @return the value of logs.log_date
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logs.log_date
     *
     * @param logDate the value for logs.log_date
     *
     * @mbggenerated Tue Apr 07 01:20:15 CST 2020
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }
}